### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by planet4** [aserramonner/MMM-HASS#1]
Thanks for sharing. I am trying this module but wont get any data. I just do not understand how you can fetch the data without any api key or login/password. Is there anything I missed?

**Comment by Flagun** [comment]
Hi, 
I had the same problem but I've found the solution. 
Go to your module location open node_helper.s file 

change these lines: 

`    var url = config.host + ':' + config.port +
              '/api/states/' + devicename;`

to: 

`    var url = config.host + ':' + config.port +
              '/api/states/' + devicename + '?api_password=yourpassword';`

and these:

`    var url = config.host + ':' + config.port +
              '/api/services/' + domain + '/' + service;`

to:

`    var url = config.host + ':' + config.port +
              '/api/services/' + domain + '/' + service + '?api_password=yourpassword';`

Cheers

**Comment by PauloPC** [comment]
I have  same situation.
Did you had updated HA recently? I did.
![capturar](https://user-images.githubusercontent.com/18357509/40837291-6bdcab2e-6570-11e8-8961-b44c82da2a04.JPG)

**Comment by sytone** [comment]
see my fork until pull #3  is completed
