### ISSUE TITLE
Swaped values

### ISSUE THREAD

**Issue by Luc3as** [aserramonner/MMM-HASS#5]
Hello, I have strange behaviour here, sometimes the values from HASS are changed between each other.
I am pulling 2 values and sometimes are OK, but then suddenly it refresh and they are at wrong places.
![image](https://user-images.githubusercontent.com/6381468/46997407-e4f12380-d11f-11e8-9946-0970f8dc20f2.png)
I mean 44 is humidity and temp is 21.4

config is as follows
```
 {
			module: "MMM-HASS",
			position: "top_right",
			config: {
					host: "host",
					port: "port",
					apipassword:"pass",
					https: true,
					devices: [
					{ deviceLabel: "Kúpelňa",
							deviceReadings: [
							{ sensor: "sensor.teplota_kupelna", icon: "wi wi-thermometer", suffix: "°"},
							{ sensor: "sensor.vlkhost_kupelna", icon: "wi wi-humidity", suffix: "%"},
							]
					},
					{ deviceLabel: "Obývačka",
							deviceReadings: [
							{ sensor: "sensor.teplota_obyvacka", icon: "wi wi-thermometer", suffix: "°", notification: "INDOOR_TEMPERATURE"},
							{ sensor: "sensor.vlhkost_obyvacka", icon: "wi wi-humidity", suffix: "%"},
							]
					},
					]
			}
		},
```

**Comment by aserramonner** [comment]
Thanks for reporting. May be some kind of race condition. I will try to find it. If you can determine under which circumstances the issue appears I would be grateful.

**Comment by WalterWampe** [comment]
Can confirm, had this problem as well. But not sure under which circumstances. Will report if found out!
Thanks for you work!!

**Comment by aserramonner** [comment]
Should be fixed now.
