### ISSUE TITLE
401: Unauthorized when using long lived access token

### ISSUE THREAD

**Issue by aforch** [aserramonner/MMM-HASS#9]
I've cloned the latest version and updated the config as per the documentation:

host: "192.168.x.x",
port: "8123",
hassiotoken: true,
https: false,
debuglogging: true,

and have set the HASSIO_TOKEN environment variable with the long lived access token generated within HASS:
echo $HASSIO_TOKEN
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.<full token redacted>

In the logs I've got:
{ deviceLabel: 'Storage Room Window',
  deviceReadings: 
    [ { sensor: 'binary_sensor.storage_room_window',
         icon: 'wi wi-moon-new',
         suffix: '' } ] }
192.168.1.152:8123/api/states/binary_sensor.storage_room_window
Request URL: http://192.168.1.152:8123/api/states/binary_sensor.storage_room_window
null
401: Unauthorized
{ undefined: undefined, label: 'Storage Room Window' }

Am I missing something? The documentation is a bit light and it seems that all of the pieces should be in place for the access token to work.

**Comment by aforch** [comment]
Solution for anyone else facing this issue:
You must create an .env file in the MMM-HASS directory (I called mine MMM-HASS.env) with your access token in it like so:
`    HASSIO_TOKEN = '<token string>' `

and then run pm2 restart mm --update-env if using pm2 for service management

**Comment by bachoo786** [comment]
I followed your way but I get my sensors as undefined.

Also in my env file for my token, do I need to put these brackets "<"      ">"

Thanks.

**Comment by bachoo786** [comment]
Just checked my logs getting the same 401 unauthorized errors as you.

I did use in my env file the brackets mentioned in my previous comments but it doenst make a difference with or without brackets as I get the same error.

Any help please?

**Comment by bachoo786** [comment]
Are you using long lived tokens or ? I am using long lived tokens

**Comment by aforch** [comment]
Using long lived token, yes. Do not use brackets around your token in the env file, just make sure the token is in single quotes and the env file is in the folder of the module.
Then make sure that you have "hassiotoken: true," in your module config, and run "pm2 restart mm --update-env" to make sure that the environment variable is loaded.

**Comment by bachoo786** [comment]
Is this for hassio or long lived tokens?

**Comment by aforch** [comment]
Everything I'm referring to is on the magic mirror host. The "hassiotoken: true," line needs to be in the config for the MMM-HASS module in config.js

**Comment by bachoo786** [comment]
Then my config.js is no different to yours. I get the 401 unauthorised error.

**Comment by aforch** [comment]
Are you using pm2 to manage the magic mirror service? If yes, did you run the command to update the environment variables?

**Comment by bachoo786** [comment]
yes i am using pm2 and i did use the command to update the environment variables too

**Comment by bachoo786** [comment]
can you please post your config.js for the hass part?

**Comment by aforch** [comment]
Here is my full config:
(IP address removed)
```
{
                        module: "MMM-HASS",
                        position: "right",
                        config: {
                                host: "0.0.0.0",
                                port: "8123",
                                hassiotoken: true,
                                https: false,
                                //debuglogging: true,
                                devices: [
                                { deviceLabel: "Kitchen Window",
                                        deviceReadings: [
                                        { sensor: "binary_sensor.kitchen_window", icon: "wi wi-moon-new", suffix: ""},
                                        ]
                                },
                                { deviceLabel: "Living Room Door",
                                        deviceReadings: [
                                        { sensor: "binary_sensor.living_room_door", icon: "wi wi-moon-new", suffix: ""},
                                        ]
                                },
                                { deviceLabel: "Laundry Room Window",
                                        deviceReadings: [
                                        { sensor: "binary_sensor.laundry_window", icon: "wi wi-moon-new", suffix: "" },
                                        ]
                                },
                                { deviceLabel: "Office Window",
                                        deviceReadings: [
                                        { sensor: "binary_sensor.office_window", icon: "wi wi-moon-new", suffix: "" },
                                        ]
                                },
                                { deviceLabel: "Storage Room Window",
                                        deviceReadings: [
                                        { sensor: "binary_sensor.front_door", icon: "wi wi-moon-new", suffix: ""},
                                        ]
                                }
                                ]
                        }
                },
```

**Comment by bachoo786** [comment]
I think my issue must be to with my HA.

I have api: and http: in my configuration.yaml

I have never set up restful api as I do not know how to use it. 

How is your HA configured for MM?

**Comment by aforch** [comment]
There is no HA configuration necessary, aside from generating the long lived access token. I have only "http:" in my configuration.yaml file. 
I previously had
```
http:
  api_password: !secret api_password
```
When using the legacy API password, but since moving to long lived access tokens that api_password command has been removed.

**Comment by bachoo786** [comment]
Right

So under my http: I have my base url as https.xxx.duckdns.org

I am sure the https and duckdns don't affect anything as my HA is accessible via the HA ip on port 8123

**Comment by bachoo786** [comment]
I have literally used your config and everything is same as yours.

I get this error in my HA log:

`2018-12-30 13:43:33 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.26`

192.168.0.26 is my rpi running MM.

 and my MM log for HA shows the following:

```
0|mm  |   deviceReadings:
0|mm  |    [ { sensor: 'sensor.weather', icon: 'wi wi-moon-new', suffix: '' } ] }
0|mm  | 192.168.0.60:8123/api/states/sensor.weather
0|mm  | Request URL: http://192.168.0.60:8123/api/states/sensor.weather
0|mm  | null
0|mm  | 401: Unauthorized
0|mm  | { undefined: undefined, label: 'Kitchen Window' }
0|mm  | null
```
all the errors keep on looping.

**Comment by bachoo786** [comment]
Are you using nginx to access your HA ? How do you access it?

**Comment by aforch** [comment]
Everything is local, I intentionally do not expose it to the internet thus no nginx/port forwarding/SSL. Do you have "https: true" in your config.js?

**Comment by bachoo786** [comment]
oh right I see

nope https is set to false.

what is https used for anyway? because I put my ip address of my HA and 8123 as the port. I can access my HA using  http://IPADDRESS:8123 anyway.

**Comment by bachoo786** [comment]
when I go to when I try https://xxx.duckdns.org/api/states I get `401: Unauthorised`

even when I try http://IPADDRESS:8123/api/states I get `401:Unathorised`

**Comment by aforch** [comment]
yeah, because you either need to pass the api password in the url string (if legacy API is enabled) or pass the long lived access token when connecting. By entering the above address in a browser you're doing neither. 
I don't know much about the whole duckdns and encryption thing with HASS, you may want to start a thread on the MM or HASS forums and ask there.

**Comment by bachoo786** [comment]
Ok great thanks for your help
